readarr api service

diff --git a/charts/arr-stack/templates/jobs/arr-secret.yaml b/charts/arr-stack/templates/jobs/arr-secret.yaml
--- a/charts/arr-stack/templates/jobs/arr-secret.yaml
+++ b/charts/arr-stack/templates/jobs/arr-secret.yaml
@@ -23,6 +23,8 @@ spec:
             value: /config/sonarr/config.xml
           - name: PROWLARR_CONFIG
             value: /config/prowlarr/config.xml
+          - name: READARR_CONFIG
+            value: /config/readarr/config.xml
         command: ["/bin/sh", "-c"]
         args:
           - |
@@ -56,12 +58,20 @@ spec:
             fi
             PROWLARR_API=$(sed -n 's/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p' "$PROWLARR_CONFIG")
 
+            echo "getting readarr..."
+            if [ ! -f "$READARR_CONFIG" ]; then
+              echo "Error: config not found at $READARR_CONFIG"
+              exit 1
+            fi
+            READARR_API=$(sed -n 's/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p' "$READARR_CONFIG")
+
             echo "applying to secret..."
             kubectl create secret generic $SECRET_NAME \
               --from-literal=LIDARR_API=$LIDARR_API \
               --from-literal=RADARR_API=$RADARR_API \
               --from-literal=SONARR_API=$SONARR_API \
               --from-literal=PROWLARR_API=$PROWLARR_API \
+              --from-literal=READARR_API=$READARR_API \
               --dry-run=client -o yaml | kubectl apply -f -
 
             echo "Done."
@@ -81,6 +91,9 @@ spec:
         - name: bazarr-config
           mountPath: /config/bazarr
           readOnly: true
+        - name: readarr-config
+          mountPath: /config/readarr
+          readOnly: true
       restartPolicy: OnFailure
       volumes:
       - name: sonarr-config
@@ -98,3 +111,6 @@ spec:
       - name: bazarr-config
         persistentVolumeClaim:
           claimName: bazarr-config
+      - name: readarr-config
+        persistentVolumeClaim:
+          claimName: readarr-config
